const staticData = [
    {
      _id: { $oid: "6397203ae13abbf3929314ee" },
      firstName: "",
      lastName: "",
      fullName: "Saikib Hossain",
      email: "",
      nid: "89465213200",
      fatherName: "",
      motherName: "",
      dateOfBirth: "1997-03-03",
      profession: "",
      phoneNumber: "01413897412",
      parmanentAddress: "",
      currentAddress: "",
      profilePicture: "",
      password: "",
      username: "",
      sex: "",
      infoProvider: "by User",
      uuid: "",
      register: null,
      joinDate: "",
      invitationResponseDate: "",
      creatorId: "",
      pendingInvitation: false,
      updateHistoryList: [],
      role: "",
      roleCode: -1,
      roleId: "",
      userType: "",
      userTypeCode: -1,
      userTypeId: "",
      isInvitation: false,
      otpLogin: false,
      isComplete: false,
      activationDate: "",
      creator: "",
      updateDate: "",
      creationDate: { $date: "2022-12-12T12:36:10.876Z" },
      status: true,
      active: true,
      delete: false,
      deleteDate: "",
      deletedById: "",
    },
    {
      _id: { $oid: "6397203ae13abbf3929314ff" },
      firstName: "John",
      lastName: "Doe",
      fullName: "John Doe",
      email: "john.doe@example.com",
      nid: "98765432101",
      fatherName: "Father Name",
      motherName: "Mother Name",
      dateOfBirth: "1990-05-12",
      profession: "Software Engineer",
      phoneNumber: "01122334455",
      parmanentAddress: "123 Main St, City, Country",
      currentAddress: "456 Another St, City, Country",
      profilePicture: "profile_pic_url",
      password: "password123",
      username: "john_doe",
      sex: "Male",
      infoProvider: "by Admin",
      uuid: "user-uuid-1",
      register: null,
      joinDate: "2021-01-01",
      invitationResponseDate: "2021-01-02",
      creatorId: "creator-id",
      pendingInvitation: false,
      updateHistoryList: [],
      role: "Admin",
      roleCode: 1,
      roleId: "admin-role-id",
      userType: "Paid",
      userTypeCode: 1,
      userTypeId: "user-type-id",
      isInvitation: false,
      otpLogin: true,
      isComplete: true,
      activationDate: "2021-02-01",
      creator: "admin",
      updateDate: "2022-01-01",
      creationDate: { $date: "2021-01-01T12:00:00.000Z" },
      status: true,
      active: true,
      delete: false,
      deleteDate: "",
      deletedById: "",
    },
    {
      _id: { $oid: "6397203ae13abbf3929314gg" },
      firstName: "Jane",
      lastName: "Smith",
      fullName: "Jane Smith",
      email: "jane.smith@example.com",
      nid: "12345678901",
      fatherName: "Father Name",
      motherName: "Mother Name",
      dateOfBirth: "1992-08-25",
      profession: "Doctor",
      phoneNumber: "01234567890",
      parmanentAddress: "789 Health St, City, Country",
      currentAddress: "321 Wellness St, City, Country",
      profilePicture: "profile_pic_url_2",
      password: "password456",
      username: "jane_smith",
      sex: "Female",
      infoProvider: "by Admin",
      uuid: "user-uuid-2",
      register: null,
      joinDate: "2022-03-15",
      invitationResponseDate: "2022-03-16",
      creatorId: "creator-id-2",
      pendingInvitation: true,
      updateHistoryList: [],
      role: "User",
      roleCode: 2,
      roleId: "user-role-id",
      userType: "Free",
      userTypeCode: 0,
      userTypeId: "user-type-id-2",
      isInvitation: true,
      otpLogin: false,
      isComplete: false,
      activationDate: "",
      creator: "admin",
      updateDate: "2023-01-01",
      creationDate: { $date: "2022-03-15T12:00:00.000Z" },
      status: false,
      active: false,
      delete: false,
      deleteDate: "",
      deletedById: "",
    },
    // Add more data as needed
  ];
  
  export default staticData;
  